### ISSUE TITLE
Windows EOLs break shebang

### ISSUE THREAD

**Issue by raphinesse** [eight04/sync-version#1]
The tool does not work under Linux, because of the Windows-EOL characters:
```
$ node_modules/.bin/sync-version bower.json
/usr/bin/env: ‘node\r’: No such file or directory
```

As a general suggestion based on my own experience: only use Unix EOLs (`LF`) for code, ever.

I cannot file a PR with a fix, since the problem seems to be how the package is published on npm.
When I clone the repo on my Linux system, I get Unix EOLs.

**Comment by eight04** [comment]
Interesting... I thought git should handle this automatically.

Now I wonder if this affect all my repos 😨

**Comment by eight04** [comment]
I got it. This is caused by npm not git.
https://github.com/npm/npm/issues/12371

Maybe it's time to use some CI services.

**Comment by raphinesse** [comment]
If the CI would have cloned the repo using git, it wouldn't have caught this either. That's a sneaky bug, for sure.

But as long as you just work with `LF` everything should be fine. The prepublish hook in the script seems like a good idea. I just have my editor configured to always produce `LF`. Alternatively, you could configure it per project, using [editorconfig](http://editorconfig.org/). And then you can of course also [make ESLint yell at you](http://eslint.org/docs/rules/linebreak-style) if you manage to sneak in some `CRLF` anyway :wink:

**Comment by eight04** [comment]
Try v1.0.1

**Comment by raphinesse** [comment]
Works like a charm! Thanks for the quick resolution.
